### ISSUE TITLE
Remove absolute path

### ISSUE THREAD

**Issue by kankaristo** [andystanton/linter-glsl#2]
Could the default path be changed to be `glslangValidator` instead of `/usr/local/bin/glslangValidator`?

The former would probably be a better default, since `/usr/local/bin/` is probably in the user's `PATH` anyway, but the executable may also be somewhere else (for me it's in `~/.bin/`, which I've added to my `PATH`).

**Comment by andystanton** [comment]
You're correct. There is no reason to keep it as ```/usr/local/bin``` so this change is also in 1.0.2.

**Comment by kankaristo** [comment]
Alright, cool! :+1:
